// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc9555.BenAutoTest.commands;


import edu.wpi.first.wpilibj.command.CommandGroup;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import org.usfirst.frc9555.BenAutoTest.Robot;
import org.usfirst.frc9555.BenAutoTest.RobotMap;

/**
 *
 */
public class AutonomousCommand extends CommandGroup {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public AutonomousCommand() {

    	if ((SmartDashboard.getBoolean("DB/Button 1", true)) && (SmartDashboard.getBoolean("DB/Button 2", false) && (SmartDashboard.getBoolean("DB/Button 3", false)))) { 
    		
    		RobotMap.motorMotor1.set(.3);
    		
    	} else if (SmartDashboard.getBoolean("DB/Button 1", false) && (SmartDashboard.getBoolean("DB/Button 2", true) && (SmartDashboard.getBoolean("DB/Button 3", false)))) {
    		
    		RobotMap.motorMotor1.set(-.3);
	
    	} else if (SmartDashboard.getBoolean("DB/Button 1", false) && (SmartDashboard.getBoolean("DB/Button 2", false) && (SmartDashboard.getBoolean("DB/Button 3", true)))) {
    		
    		RobotMap.motorMotor1.set(1);
	
    	} else {
    		
    		RobotMap.motorMotor1.set(-1);
    		
    	}

    }
    
}
